apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://localhost:6443
    k8sVersion: v1.9.6
    path: default
kind: ksonnet.io/app
libraries:
  prometheus-operator:
    name: prometheus-operator
    registry: kube-prometheus
name: kp
registries:
  kube-prometheus:
    protocol: fs
    uri: /Users/bryan/Development/heptio/ksonnet-prometheus
version: 0.0.1
